version: "3"
services:
  tests:
    build: .
    command: python -m pytest -m ui --alluredir=./allure-results
    volumes:
      - .:/code
    env_file:
      - .env
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    networks:
      - selenium
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7900:7900"

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    networks:
      - selenium
    ports:
      - "4444:4444"

networks:
  selenium:
    name: selenium
